In [7]:
sales = [555,856,953,756,842,445]
profite = [123,365,245,152,263,225]

In [8]:
import numpy as rs


In [11]:
profite_array = rs.array(profite)

In [12]:
profite_array/sales_array

array([0.22162162, 0.42640187, 0.2570829 , 0.2010582 , 0.31235154,
       0.50561798])

In [14]:
sales*3

[555,
 856,
 953,
 756,
 842,
 445,
 555,
 856,
 953,
 756,
 842,
 445,
 555,
 856,
 953,
 756,
 842,
 445]

In [16]:
sales_array*3

array([1665, 2568, 2859, 2268, 2526, 1335])

In [18]:
sales_array_1 = sales_array[0:3]

In [19]:
sales_array_1

array([555, 856, 953])

In [21]:
sales_array_1[0]=0

In [22]:
sales_array_1

array([  0, 856, 953])

In [25]:
list1 = [53,25,58,'Ram',145]

In [26]:
rs.array(list1)

array(['53', '25', '58', 'Ram', '145'], dtype='<U11')

In [27]:
mydata = rs.arange(0,20)

In [28]:
mydata

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
matrix1 = rs.reshape(mydata,(5,4))

In [30]:
matrix1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [31]:
sale_us = [1221,2995,2883,3886,7725]
sale_as = [1475,8145,3243,2596,7545]
sale_jp = [1111,2745,2143,3156,2523]

In [32]:
sales_matrix =rs.array([sale_us,sale_as,sale_jp])

In [33]:
sales_matrix

array([[1221, 2995, 2883, 3886, 7725],
       [1475, 8145, 3243, 2596, 7545],
       [1111, 2745, 2143, 3156, 2523]])

In [42]:
profite_us = [11,29,28,36,25]
profite_as = [75,85,43,96,75]
profite_jp = [21,45,23,56,27]

In [35]:
profite_matrix =rs.array([profite_us,profite_as,profite_jp])

In [43]:
profite_matrix

array([[11, 29, 28, 36, 25],
       [77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77]])

In [37]:
sales_matrix/profite_matrix

array([[111.        , 103.27586207, 102.96428571, 107.94444444,
        309.        ],
       [ 19.66666667,  95.82352941,  75.41860465,  27.04166667,
        100.6       ],
       [ 52.9047619 ,  61.        ,  93.17391304,  56.35714286,
         93.44444444]])

In [38]:
profite_matrix[1:3]=77

In [39]:
profite_matrix

array([[11, 29, 28, 36, 25],
       [77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77]])

In [44]:
Quarter = ['Q1','Q2','Q3','Q4']
Region = ['US','AS','JP']

In [45]:
qdict = {'Q1':0,'Q2':1,'Q3':2,'Q4':3}
rdict = {'US':0,'AS':1,'JP':2}

In [46]:
sales_matrix[rdict['JP']][qdict['Q3']]

2143

In [79]:
raw_data ={'cust_id': [1,2,3,4],
          'First_name':['A','B','C','D'],
          'Last_name':['x','y','z','w']}

In [75]:
import pandas as pd

In [80]:
cust_detail = pd.DataFrame(raw_data)

In [81]:
cust_detail

cust_id First_name Last_name
0        1          A         x
1        2          B         y
2        3          C         z
3        4          D         w

In [82]:
sales_data ={'cust_id': [1,2,3,5],
          'sales':['1582','2536','2456','1425'],
          'Product':['TV','Playstaion','AC','Computer']}

In [85]:
sales_detail = pd.DataFrame(sales_data)

In [86]:
sales_detail

cust_id sales     Product
0        1  1582          TV
1        2  2536  Playstaion
2        3  2456          AC
3        5  1425    Computer

In [88]:
pd.concat([cust_detail,sales_detail],axis=0)

C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


First_name Last_name     Product  cust_id sales
0          A         x         NaN        1   NaN
1          B         y         NaN        2   NaN
2          C         z         NaN        3   NaN
3          D         w         NaN        4   NaN
0        NaN       NaN          TV        1  1582
1        NaN       NaN  Playstaion        2  2536
2        NaN       NaN          AC        3  2456
3        NaN       NaN    Computer        5  1425

In [89]:
pd.concat([cust_detail,sales_detail],axis=1)

cust_id First_name Last_name  cust_id sales     Product
0        1          A         x        1  1582          TV
1        2          B         y        2  2536  Playstaion
2        3          C         z        3  2456          AC
3        4          D         w        5  1425    Computer

In [90]:
pd.merge(cust_detail,sales_detail, left_on='cust_id', right_on='cust_id', how='right')

cust_id First_name Last_name sales     Product
0        1          A         x  1582          TV
1        2          B         y  2536  Playstaion
2        3          C         z  2456          AC
3        5        NaN       NaN  1425    Computer

In [91]:
pd.merge(cust_detail,sales_detail, left_on='cust_id', right_on='cust_id', how='left')

cust_id First_name Last_name sales     Product
0        1          A         x  1582          TV
1        2          B         y  2536  Playstaion
2        3          C         z  2456          AC
3        4          D         w   NaN         NaN

In [92]:
pd.merge(cust_detail,sales_detail, left_on='cust_id', right_on='cust_id', how='outer')

cust_id First_name Last_name sales     Product
0        1          A         x  1582          TV
1        2          B         y  2536  Playstaion
2        3          C         z  2456          AC
3        4          D         w   NaN         NaN
4        5        NaN       NaN  1425    Computer

In [94]:
pd.merge(cust_detail,sales_detail, left_on='cust_id', right_on='cust_id', how='inner')

cust_id First_name Last_name sales     Product
0        1          A         x  1582          TV
1        2          B         y  2536  Playstaion
2        3          C         z  2456          AC